var fs = require("fs");

var code = [
  'require("dotenv").config();',
  '',
  'var express = require("express");',
  'var cors = require("cors");',
  'var jwt = require("jsonwebtoken");',
  'var multer = require("multer");',
  'var Pool = require("pg").Pool;',
  '',
  'var app = express();',
  'var PORT = process.env.PORT || 3000;',
  'var JWT_SECRET = process.env.JWT_SECRET || "dev_secret";',
  '',
  'var pool = new Pool({ connectionString: process.env.DATABASE_URL });',
  '',
  'app.use(cors());',
  'app.use(express.json({ limit: "50mb" }));',
  'app.use(express.urlencoded({ limit: "50mb", extended: true }));',
  '',
  'function auth(req, res, next) {',
  '  var header = req.headers.authorization;',
  '  if (!header) return res.status(401).json({ message: "No token" });',
  '  try {',
  '    var token = header.split(" ")[1];',
  '    req.user = jwt.verify(token, JWT_SECRET);',
  '    next();',
  '  } catch (e) {',
  '    return res.status(401).json({ message: "Invalid token" });',
  '  }',
  '}',
  '',
  'var upload = multer({',
  '  storage: multer.memoryStorage(),',
  '  limits: { fileSize: 10 * 1024 * 1024 },',
  '});',
  '',
  'app.get("/", function (req, res) {',
  '  res.json({ status: "OK" });',
  '});',
  '',
  'app.get("/run-migration", async function (req, res) {',
  '  try {',
  '    await pool.query("CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, name TEXT, email TEXT UNIQUE NOT NULL, password TEXT, role TEXT DEFAULT \'candidate\', current_job_title TEXT, specialization TEXT, profile_summary TEXT, photo_url TEXT, cv_url TEXT, technical_skills TEXT[], soft_skills TEXT[], experience TEXT, education TEXT, courses TEXT, certificates TEXT, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW())");',
  '    await pool.query("CREATE TABLE IF NOT EXISTS jobs (id SERIAL PRIMARY KEY, title TEXT NOT NULL, description TEXT, qualifications TEXT, location TEXT, company_name TEXT, experience_years INTEGER, posted_by INTEGER REFERENCES users(id) ON DELETE SET NULL, created_at TIMESTAMP DEFAULT NOW())");',
  '    await pool.query("CREATE TABLE IF NOT EXISTS applications (id SERIAL PRIMARY KEY, user_id INTEGER REFERENCES users(id) ON DELETE CASCADE, job_id INTEGER REFERENCES jobs(id) ON DELETE CASCADE, status TEXT DEFAULT \'applied\', applied_at TIMESTAMP DEFAULT NOW())");',
  '    await pool.query("ALTER TABLE users ADD COLUMN IF NOT EXISTS technical_skills TEXT[]");',
  '    await pool.query("ALTER TABLE users ADD COLUMN IF NOT EXISTS soft_skills TEXT[]");',
  '    await pool.query("ALTER TABLE users ADD COLUMN IF NOT EXISTS experience TEXT");',
  '    await pool.query("ALTER TABLE users ADD COLUMN IF NOT EXISTS education TEXT");',
  '    await pool.query("ALTER TABLE users ADD COLUMN IF NOT EXISTS courses TEXT");',
  '    await pool.query("ALTER TABLE users ADD COLUMN IF NOT EXISTS certificates TEXT");',
  '    await pool.query("ALTER TABLE jobs ADD COLUMN IF NOT EXISTS experience_years INTEGER");',
  '    var c = await pool.query("SELECT column_name FROM information_schema.columns WHERE table_name = \'users\' AND column_name = \'password_hash\'");',
  '    if (c.rows.length > 0) {',
  '      await pool.query("ALTER TABLE users RENAME COLUMN password_hash TO password");',
  '    }',
  '    var r = await pool.query("SELECT column_name FROM information_schema.columns WHERE table_name = \'users\'");',
  '    res.json({ status: "SUCCESS", total_columns: r.rows.length, columns: r.rows.map(function (x) { return x.column_name; }) });',
  '  } catch (e) {',
  '    res.status(500).json({ status: "FAILED", error: e.message });',
  '  }',
  '});',
  '',
  'app.post("/auth/login", async function (req, res) {',
  '  try {',
  '    var result = await pool.query("INSERT INTO users (email, role) VALUES (\'dev@example.com\', \'candidate\') ON CONFLICT (email) DO UPDATE SET email = EXCLUDED.email RETURNING id");',
  '    var token = jwt.sign({ userId: result.rows[0].id }, JWT_SECRET, { expiresIn: "7d" });',
  '    res.json({ token: token });',
  '  } catch (e) {',
  '    res.status(500).json({ error: e.message });',
  '  }',
  '});',
  '',
  'app.post("/candidates/upload/photo", auth, upload.single("photo"), async function (req, res) {',
  '  if (!req.file) return res.status(400).json({ error: "Photo required" });',
  '  var b = req.file.buffer.toString("base64");',
  '  var d = "data:" + req.file.mimetype + ";base64," + b;',
  '  await pool.query("UPDATE users SET photo_url = $1 WHERE id = $2", [d, req.user.userId]);',
  '  res.json({ photo_url: d });',
  '});',
  '',
  'app.post("/candidates/upload/cv", auth, upload.single("cv"), async function (req, res) {',
  '  if (!req.file) return res.status(400).json({ error: "CV required" });',
  '  var b = req.file.buffer.toString("base64");',
  '  var d = "data:application/pdf;base64," + b;',
  '  await pool.query("UPDATE users SET cv_url = $1 WHERE id = $2", [d, req.user.userId]);',
  '  res.json({ cv_url: d });',
  '});',
  '',
  'app.get("/candidates/me", auth, async function (req, res) {',
  '  var r = await pool.query("SELECT * FROM users WHERE id = $1", [req.user.userId]);',
  '  res.json(r.rows[0] || {});',
  '});',
  '',
  'app.post("/candidates/me", auth, async function (req, res) {',
  '  var b = req.body;',
  '  await pool.query("UPDATE users SET name = $1, current_job_title = $2, specialization = $3, profile_summary = $4, photo_url = $5, cv_url = $6, updated_at = NOW() WHERE id = $7", [b.name, b.current_job_title, b.specialization, b.profile_summary, b.photo_url, b.cv_url, req.user.userId]);',
  '  res.json({ success: true });',
  '});',
  '',
  'app.listen(PORT, function () {',
  '  console.log("Backend running on port " + PORT);',
  '  pool.query("CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, name TEXT, email TEXT UNIQUE NOT NULL, password TEXT, role TEXT DEFAULT \'candidate\', current_job_title TEXT, specialization TEXT, profile_summary TEXT, photo_url TEXT, cv_url TEXT, technical_skills TEXT[], soft_skills TEXT[], experience TEXT, education TEXT, courses TEXT, certificates TEXT, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW())")',
  '  .then(function () { console.log("users table OK"); return pool.query("CREATE TABLE IF NOT EXISTS jobs (id SERIAL PRIMARY KEY, title TEXT NOT NULL, description TEXT, qualifications TEXT, location TEXT, company_name TEXT, experience_years INTEGER, posted_by INTEGER REFERENCES users(id) ON DELETE SET NULL, created_at TIMESTAMP DEFAULT NOW())"); })',
  '  .then(function () { console.log("jobs table OK"); return pool.query("CREATE TABLE IF NOT EXISTS applications (id SERIAL PRIMARY KEY, user_id INTEGER REFERENCES users(id) ON DELETE CASCADE, job_id INTEGER REFERENCES jobs(id) ON DELETE CASCADE, status TEXT DEFAULT \'applied\', applied_at TIMESTAMP DEFAULT NOW())"); })',
  '  .then(function () { console.log("applications table OK"); return pool.query("ALTER TABLE users ADD COLUMN IF NOT EXISTS technical_skills TEXT[]"); })',
  '  .then(function () { return pool.query("ALTER TABLE users ADD COLUMN IF NOT EXISTS soft_skills TEXT[]"); })',
  '  .then(function () { return pool.query("ALTER TABLE users ADD COLUMN IF NOT EXISTS experience TEXT"); })',
  '  .then(function () { return pool.query("ALTER TABLE users ADD COLUMN IF NOT EXISTS education TEXT"); })',
  '  .then(function () { return pool.query("ALTER TABLE users ADD COLUMN IF NOT EXISTS courses TEXT"); })',
  '  .then(function () { return pool.query("ALTER TABLE users ADD COLUMN IF NOT EXISTS certificates TEXT"); })',
  '  .then(function () { return pool.query("ALTER TABLE jobs ADD COLUMN IF NOT EXISTS experience_years INTEGER"); })',
  '  .then(function () { return pool.query("SELECT column_name FROM information_schema.columns WHERE table_name = \'users\' AND column_name = \'password_hash\'"); })',
  '  .then(function (c) { if (c.rows.length > 0) return pool.query("ALTER TABLE users RENAME COLUMN password_hash TO password"); })',
  '  .then(function () { return pool.query("SELECT column_name FROM information_schema.columns WHERE table_name = \'users\'"); })',
  '  .then(function (r) { console.log("Migration done! Users table has " + r.rows.length + " columns"); })',
  '  .catch(function (e) { console.log("Migration error: " + e.message); });',
  '});',
].join("\n");

fs.writeFileSync("index.js", code);
console.log("index.js written successfully!");